M48
; DRILL file {KiCad 9.0.9-9.0.9~ubuntu24.04.1} date 2026-08-02T14:39:42+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-08-02T14:39:42+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.9-9.0.9~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.400
%
G90
G05
T1
X7.0Y-7.27
X7.0Y-13.05
T2
X1.5Y-1.26
X1.5Y-19.06
X54.38Y-1.26
X54.38Y-19.06
M30
